# Generated by Django 5.0.6 on 2024-05-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features_graph',
            old_name='percent',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='features_graph',
            old_name='feature',
            new_name='name',
        ),
    ]
