# Generated by Django 5.0.6 on 2024-05-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphing', '0002_rename_percent_features_graph_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('count', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Features_Graph',
        ),
    ]
